package Model;

/** This class supplies the customer object. */
public  class Customer {
    private int customerId;
    private String customerName;
    private String address;
    private String postalCode;
    private String phone;
    private String createDate;
    private String createdBy;
    private String lastUpdate;
    private String lastUpdateBy;
    private int divisionId;


/** Constructor for an instance of the appointment schedule object.
 *
 * @param createDate date the transaction was created
 * @param createdBy the user who created the transaction
 * @param lastUpdate the date the transaction was updated
 * @param customerId customer ID generated by the database
 * @param lastUpdateBy the user who last updated the transaction
 * @param divisionId the division ID
 * @param address the customer address
 * @param customerName the customer name
 * @param phone the customer phone number
 * @param postalCode the customer zipcode
 *
 * */
    public Customer(int customerId, String customerName, String address, String postalCode, String phone, String createDate, String createdBy, String lastUpdate, String lastUpdateBy, int divisionId) {
        this.customerId = customerId;
        this.customerName = customerName;
        this.address = address;
        this.postalCode = postalCode;
        this.phone = phone;
        this.createDate = createDate;
        this.createdBy = createdBy;
        this.lastUpdate = lastUpdate;
        this.lastUpdateBy = lastUpdateBy;
        this.divisionId = divisionId;
    }


    public Customer() {
        this.customerId = 0;
        this.customerName = "";
        this.address = "";
        this.postalCode = "";
        this.phone = "";
        this.createDate = "";
        this.createdBy = "";
        this.lastUpdate = "";
        this.lastUpdateBy = "";
        this.divisionId = 0;
    }

    /** The customer name getter.
     *
     * @return customer name
     *
     */
    public String getCustomerName() {
        return customerName;
    }

    /** Customer name  setter. */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /** The address getter.
     *
     * @return address
     *
     */
    public String getAddress() {
        return address;
    }

    /** Address setter. */
    public void setAddress(String address) {
        this.address = address;
    }

    /** The postal code getter.
     *
     * @return postal code
     *
     */
    public String getPostalCode() {
        return postalCode;
    }

    /** Postal code setter. */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /** The phone getter.
     *
     * @return phone
     *
     */
    public String getPhone() {
        return phone;
    }

    /** Phone setter. */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /** The customer ID getter.
     *
     * @return customer ID
     *
     */
    public int getCustomerId() {
        return customerId;
    }

    /** Customer ID setter. */
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    /** The create date getter.
     *
     * @return create date
     *
     */
    public String getCreateDate() {
        return createDate;
    }

    /** create date setter. */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /** The created by getter.
     *
     * @return created by
     *
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /** Created by setter. */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /** The last update getter.
     *
     * @return last update
     *
     */
    public String getLastUpdate() {
        return lastUpdate;
    }

    /** Last update setter. */
    public void setLastUpdate(String lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /** The last update by getter.
     *
     * @return last update by
     *
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /** Last update By setter. */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }

    /** The division ID getter.
     *
     * @return division ID
     *
     */
    public int getDivisionId() {
        return divisionId;
    }

    /** Division ID setter. */
    public void setDivisionId(int divisionId) {
        this.divisionId = divisionId;
    }
}
